from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Union

import dspy

logger = logging.getLogger(__name__)

DEFAULT_MODE = "two_stage"
LM_NAME = "openai/gpt-5.4-2026-03-05"
QUERY_STRUCTURE_GUIDANCE = """Queries are generated by composing category names with set operations such as intersection, union, and difference, then rewriting the result as a natural-language query.

The query will follow one of these templates:
['_', '_ or _', '_ or _ or _', '_ that are also _',
 '_ that are also _ but not _',
 '_ that are also both _ and _',
 '_ that are not _']"""

FILTER_SELECTION_INSTRUCTIONS = f"""{QUERY_STRUCTURE_GUIDANCE}

Your task is to select metadata filters that can help pre-filter for this query.

Analyze the query's constraints and select filters that can confidently express at least some of them. This is recall-oriented pruning; vector search handles final ranking.

Return only a JSON array of filter names. If no filter clearly applies, return []."""

WHERE_PLANNING_INSTRUCTIONS = f"""{QUERY_STRUCTURE_GUIDANCE}

Your task is to map the query to a ChromaDB where-clause using the filter catalog.
This is RECALL-ORIENTED pruning — the filter's only job is to avoid losing relevant documents. Vector search handles final ranking and precision.

Rules:
1. ALWAYS use $or as the top-level combinator. Flatten all relevant tags into a single $or list. Do NOT use $and to combine different constraints — metadata is incomplete and requiring ALL constraints filters out relevant documents.
2. Include every catalog tag that MIGHT match a relevant document. Cast a wide net. It is much better to include 200 candidates that contain all gold documents than to return 5 candidates that miss half of them.
3. For queries with exclusion ("not _", "excluding _", "but not _"), still use $or for the positive constraints. Ignore the exclusion for filtering — vector search handles it.
4. If no catalog entry clearly applies, return null.
5. Use only filters and values present in the catalog.

Return only JSON, or null if no useful filter applies."""

FEW_SHOT_EXAMPLES: List[Dict[str, Any]] = [
    {
        # subset_2: "Grape family of flowering plants"
        "template": "_",
        "question": "Grape family of flowering plants",
        "where": {
            "$or": [
                {"organism:type:plant": True},
                {"organism:type:vascular plant": True},
                {"organism:type:vine": True},
                {"organism:type:climbing plant": True},
                {"organism:type:flowering plant": True},
                {"organism:type:shrub": True},
                {"organism:type:land plant": True},
            ]
        },
    },
    {
        # subset_1: "American remakes of Danish films or about weddings in the United States"
        "template": "_ or _",
        "question": "American remakes of Danish films or about weddings in the United States",
        "where": {
            "$or": [
                {"film:country_of_origin:United States": True},
                {"film:country:United States": True},
                {"film:country_of_origin:Denmark": True},
                {"film:subject:wedding": True},
                {"film:subject:marriage": True},
                {"film:subject:romance": True},
                {"film:genre:comedy": True},
                {"film:genre:romance": True},
                {"film:genre:romantic comedy": True},
            ]
        },
    },
    {
        # subset_3: "Non-fiction books from 1858, 1863, or 1859"
        "template": "_ or _ or _",
        "question": "Non-fiction books from 1858, 1863, or 1859",
        "where": {
            "$or": [
                {"book:year": {"$eq": 1858}},
                {"book:year": {"$eq": 1859}},
                {"book:year": {"$eq": 1863}},
                {"book:publication_year": {"$eq": 1858}},
                {"book:publication_year": {"$eq": 1859}},
                {"book:publication_year": {"$eq": 1863}},
            ]
        },
    },
    {
        # subset_2: "Freshwater animals of Africa that are Endemic fauna of Angola"
        "template": "_ that are also _",
        "question": "Freshwater animals of Africa that are Endemic fauna of Angola",
        "where": {
            "$or": [
                {"animal:location:Angola": True},
                {"organism:location:Angola": True},
                {"biological_taxon:location:Angola": True},
                {"animal:location:Africa": True},
                {"organism:location:Africa": True},
                {"organism:type:fish": True},
                {"organism:type:freshwater fish": True},
                {"organism:type:ray-finned fish": True},
                {"organism:type:catfish": True},
                {"organism:type:animal": True},
            ]
        },
    },
    {
        # subset_2: "Malpighiales genera and Paleotropical flora but not Monotypic angiosperm genera"
        "template": "_ that are also _ but not _",
        "question": "Malpighiales genera and Paleotropical flora but not Monotypic angiosperm genera",
        "where": {
            "$or": [
                {"organism:type:flowering plant": True},
                {"organism:type:plant": True},
                {"organism:type:vascular plant": True},
                {"organism:type:angiosperm": True},
                {"organism:type:seed plant": True},
                {"organism:type:land plant": True},
                {"organism:type:shrub": True},
                {"organism:type:tree": True},
                {"plant_taxon:location:Tropics": True},
                {"plant_taxon:location:tropics": True},
                {"plant_taxon:location:Tropical Asia": True},
                {"plant_taxon:location:Africa": True},
                {"plant_taxon:location:Afrotropical": True},
                {"plant_taxon:location:Oceania": True},
                {"biological_taxon:location:Tropics": True},
                {"biological_taxon:location:Tropical Asia": True},
                {"biological_taxon:location:Africa": True},
                {"biological_taxon:location:Oceania": True},
                {"organism:location:Tropics": True},
            ]
        },
    },
    {
        # subset_1: "Fauna of the California chaparral, woodlands, Colorado Desert and other deserts"
        "template": "_ that are also both _ and _",
        "question": "Fauna of the California chaparral, woodlands, Colorado Desert and other deserts",
        "where": {
            "$or": [
                {"animal:location:California": True},
                {"biological_taxon:location:California": True},
                {"organism:location:California": True},
                {"animal:location:Southwestern United States": True},
                {"biological_taxon:location:Southwestern United States": True},
                {"animal:location:North America": True},
                {"organism:location:North America": True},
                {"animal:location:United States": True},
            ]
        },
    },
    {
        # subset_1: "Novels set in Vietnam excluding Novels set in the 1970s"
        "template": "_ that are not _",
        "question": "Novels set in Vietnam excluding Novels set in the 1970s",
        "where": {
            "$or": [
                {"book:setting:Vietnam": True},
                {"book:setting_location:Vietnam": True},
                {"book:setting_location:Southeast Asia": True},
                {"book:setting_location:South Vietnam": True},
                {"book:subject:Vietnam War": True},
                {"book:genre:novel": True},
                {"book:genre:fiction": True},
            ]
        },
    },
]


class FilterSelectionSignature(dspy.Signature):
    template = dspy.InputField(desc="Query template if available; otherwise an empty string.")
    query = dspy.InputField(desc="Search query.")
    available_filters = dspy.InputField(desc="JSON array of available filter names.")
    selected_filters = dspy.OutputField(desc="Return only a JSON array of selected filter names.")


class WherePlanningSignature(dspy.Signature):
    template = dspy.InputField(desc="Query template if available; otherwise an empty string.")
    query = dspy.InputField(desc="Search query.")
    filter_catalog = dspy.InputField(
        desc='JSON object mapping filter names to {type, allowed_values}; allowed_values entries include both "value" and "frequency".'
    )
    where_clause = dspy.OutputField(
        desc='Return only a JSON where-clause, or null if no metadata filter should be used.'
    )


FilterSelectionSignature.__doc__ = FILTER_SELECTION_INSTRUCTIONS
WherePlanningSignature.__doc__ = WHERE_PLANNING_INSTRUCTIONS


class FilterSelectionModule(dspy.Module):
    def __init__(self, examples: Optional[List[dspy.Example]] = None) -> None:
        super().__init__()
        self._predict = dspy.Predict(FilterSelectionSignature)
        self._examples = examples or []

    def forward(self, query: str, available_filters: str, template: str = "") -> str:
        result = self._predict(
            template=template,
            query=query,
            available_filters=available_filters,
            demos=self._examples,
        )
        return getattr(result, "selected_filters", "[]").strip()


class WherePlanningModule(dspy.Module):
    def __init__(self, examples: Optional[List[dspy.Example]] = None) -> None:
        super().__init__()
        self._predict = dspy.Predict(WherePlanningSignature)
        self._examples = examples or []

    def forward(self, query: str, filter_catalog: str, template: str = "") -> str:
        result = self._predict(
            template=template,
            query=query,
            filter_catalog=filter_catalog,
            demos=self._examples,
        )
        return getattr(result, "where_clause", "null").strip()


def _parse_json(raw: str, default: Any) -> Any:
    if not raw:
        return default
    text = raw.strip()
    if text.lower() == "null":
        return None
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except (json.JSONDecodeError, TypeError):
        logger.warning("Failed to parse JSON: %s...", raw[:120])
        return default


def _json_dumps(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True)


def _normalize_allowed_values_with_frequencies(info: Dict[str, Any]) -> List[Dict[str, Any]]:
    allowed = []
    fallback_frequency = info.get("frequency")
    for raw in info.get("allowed_values", []) or []:
        if isinstance(raw, dict):
            value = raw.get("value")
            frequency = raw.get("frequency")
        else:
            value = raw
            frequency = fallback_frequency
        if value is None:
            continue
        allowed.append({"value": value, "frequency": frequency})
    return allowed


def _format_available_filters(filter_catalog: Dict[str, Any]) -> str:
    return _json_dumps(sorted(filter_catalog))


def _format_catalog_json(
    filter_catalog: Dict[str, Any],
    selected_filters: Optional[Sequence[str]] = None,
) -> str:
    names = sorted(selected_filters) if selected_filters is not None else sorted(filter_catalog)
    payload = {
        name: {
            "type": (filter_catalog.get(name) or {}).get("type", "unknown"),
            "allowed_values": _normalize_allowed_values_with_frequencies(filter_catalog.get(name) or {}),
        }
        for name in names
        if name in filter_catalog
    }
    return _json_dumps(payload)


def _extract_demo_filters(where: Any) -> List[str]:
    filters: set[str] = set()

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key in {"$and", "$or"} and isinstance(value, list):
                    for item in value:
                        visit(item)
                    continue
                if key.startswith("$"):
                    continue
                if isinstance(value, bool) or (
                    isinstance(value, dict) and "$nin" in value and value["$nin"] == [True]
                ):
                    if ":" in key:
                        filters.add(key.rsplit(":", 1)[0])
                elif isinstance(value, dict) and any(op in value for op in ("$eq", "$gte", "$lte")):
                    filters.add(key)

    visit(where)
    return sorted(filters)


def _build_demo_catalog(where: Dict[str, Any]) -> Dict[str, Any]:
    catalog: Dict[str, Dict[str, Any]] = {}

    def add_value(filter_name: str, filter_type: str, value: Any) -> None:
        entry = catalog.setdefault(filter_name, {"type": filter_type, "allowed_values": {}})
        entry["allowed_values"][value] = entry["allowed_values"].get(value, 0) + 1

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key in {"$and", "$or"} and isinstance(value, list):
                    for item in value:
                        visit(item)
                    continue
                if key.startswith("$"):
                    continue
                if isinstance(value, bool):
                    if ":" in key:
                        base, allowed_value = key.rsplit(":", 1)
                        add_value(base, "bool", allowed_value)
                elif isinstance(value, dict) and "$nin" in value and value["$nin"] == [True]:
                    if ":" in key:
                        base, allowed_value = key.rsplit(":", 1)
                        add_value(base, "bool", allowed_value)
                elif isinstance(value, dict):
                    for op in ("$eq", "$gte", "$lte"):
                        if op in value:
                            add_value(key, "int", int(value[op]))

    visit(where)

    return {
        filter_name: {
            "type": entry["type"],
            "allowed_values": [
                {"value": value, "frequency": frequency}
                for value, frequency in sorted(entry["allowed_values"].items(), key=lambda item: str(item[0]))
            ],
        }
        for filter_name, entry in sorted(catalog.items())
    }


def _build_filter_selection_examples() -> List[dspy.Example]:
    demo_filter_list = sorted(
        {
            filter_name
            for example in FEW_SHOT_EXAMPLES
            for filter_name in _extract_demo_filters(example["where"])
        }
    )
    available_filters = _json_dumps(demo_filter_list)
    return [
        dspy.Example(
            template=example["template"],
            query=example["question"],
            available_filters=available_filters,
            selected_filters=_json_dumps(_extract_demo_filters(example["where"])),
        ).with_inputs("template", "query", "available_filters")
        for example in FEW_SHOT_EXAMPLES
    ]


def _build_planning_examples() -> List[dspy.Example]:
    return [
        dspy.Example(
            template=example["template"],
            query=example["question"],
            filter_catalog=_json_dumps(_build_demo_catalog(example["where"])),
            where_clause=_json_dumps(example["where"]),
        ).with_inputs("template", "query", "filter_catalog")
        for example in FEW_SHOT_EXAMPLES
    ]


def _normalize_selected_filters(raw: Any, filter_catalog: Dict[str, Any]) -> List[str]:
    if not isinstance(raw, list):
        return []
    seen: set[str] = set()
    selected: List[str] = []
    for value in raw:
        name = str(value)
        if name in filter_catalog and name not in seen:
            selected.append(name)
            seen.add(name)
    return selected


def _coerce_int(value: Any) -> Optional[int]:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _normalize_int_clause(key: str, value: Any, filter_catalog: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    if key not in filter_catalog or (filter_catalog.get(key) or {}).get("type") != "int":
        return None
    if not isinstance(value, dict):
        return None
    normalized = {}
    for op in ("$eq", "$gte", "$lte"):
        coerced = _coerce_int(value.get(op))
        if coerced is not None:
            normalized[op] = coerced
    if not normalized:
        return None
    return {key: normalized}


def _match_bool_filter(key: str, filter_catalog: Dict[str, Any]) -> bool:
    for filter_name, info in filter_catalog.items():
        if info.get("type") != "bool":
            continue
        prefix = f"{filter_name}:"
        if not key.startswith(prefix):
            continue
        value = key[len(prefix):]
        allowed_values = {
            str(item["value"])
            for item in _normalize_allowed_values_with_frequencies(info)
            if item.get("value") is not None
        }
        if value in allowed_values:
            return True
    return False


def _normalize_bool_clause(key: str, value: Any, filter_catalog: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    if not _match_bool_filter(key, filter_catalog):
        return None
    if isinstance(value, bool):
        return {key: value}
    if isinstance(value, dict) and value.get("$nin") == [True]:
        return {key: {"$nin": [True]}}
    return None


def _normalize_where(clause: Any, filter_catalog: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    if not isinstance(clause, dict):
        return None

    for op in ("$and", "$or"):
        if op in clause:
            items = clause.get(op)
            if not isinstance(items, list):
                return None
            normalized_items = []
            for item in items:
                normalized = _normalize_where(item, filter_catalog)
                if normalized:
                    normalized_items.append(normalized)
            if not normalized_items:
                return None
            if len(normalized_items) == 1:
                return normalized_items[0]
            return {op: normalized_items}

    normalized_terms = []
    for key, value in clause.items():
        if key.startswith("$"):
            continue
        normalized = _normalize_int_clause(key, value, filter_catalog)
        if not normalized:
            normalized = _normalize_bool_clause(key, value, filter_catalog)
        if normalized:
            normalized_terms.append(normalized)

    if not normalized_terms:
        return None
    if len(normalized_terms) == 1:
        return normalized_terms[0]
    return {"$and": normalized_terms}


class LLMQueryPlanner:
    def __init__(self, filter_catalog_path: Union[str, Path]) -> None:
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not api_key:
            raise RuntimeError("Missing OPENAI_API_KEY in environment.")

        dspy.configure(
            lm=dspy.LM(
                LM_NAME,
                temperature=1.0,
                max_tokens=16000,
                api_key=api_key,
            )
        )

        self.filter_catalog = self._load_catalog(filter_catalog_path)
        self._available_filters = _format_available_filters(self.filter_catalog)
        self._full_catalog = _format_catalog_json(self.filter_catalog)

        self._select_filters = FilterSelectionModule(
            examples=_build_filter_selection_examples(),
        )
        self._plan_where = WherePlanningModule(
            examples=_build_planning_examples(),
        )

    def _load_catalog(self, path: Union[str, Path]) -> Dict[str, Any]:
        p = Path(path)
        if not p.exists():
            logger.warning("Filter catalog not found: %s", p)
            return {}
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.error("Failed to load filter catalog: %s", exc)
            return {}

    def plan(self, query: str, mode: str = DEFAULT_MODE) -> Optional[Dict[str, Any]]:
        if not self.filter_catalog:
            return None
        results = self.plan_queries([query], mode=mode)
        return results[0] if results else None

    def plan_queries(
        self,
        queries: Sequence[str],
        mode: str = DEFAULT_MODE,
    ) -> List[Optional[Dict[str, Any]]]:
        if not self.filter_catalog:
            return [None for _ in queries]
        if mode not in {"one_shot", "two_stage"}:
            raise ValueError(f"Unsupported mode: {mode}")

        if mode == "two_stage":
            return self._plan_two_stage(queries)
        return self._plan_one_shot(queries)

    def _plan_one_shot(self, queries: Sequence[str]) -> List[Optional[Dict[str, Any]]]:
        results: List[Optional[Dict[str, Any]]] = []
        for query in queries:
            raw_where = self._plan_where(
                query=query,
                filter_catalog=self._full_catalog,
                template="",
            )
            clause = _parse_json(raw_where, default=None)
            result = _normalize_where(clause, self.filter_catalog)
            logger.info("One-shot | query=%r | clause=%s", query, json.dumps(result) if result else "null")
            results.append(result)
        return results

    def _plan_two_stage(self, queries: Sequence[str]) -> List[Optional[Dict[str, Any]]]:
        # Stage 1: Select filters for each query (7 few-shot demos per call).
        selected_per_query: List[List[str]] = []
        for query in queries:
            raw_selected = self._select_filters(
                query=query,
                available_filters=self._available_filters,
                template="",
            )
            parsed = _parse_json(raw_selected, default=[])
            selected = _normalize_selected_filters(
                parsed if isinstance(parsed, list) else [],
                self.filter_catalog,
            )
            selected_per_query.append(selected)

        # Stage 2: Plan where clause for each query (7 few-shot demos per call).
        results: List[Optional[Dict[str, Any]]] = [None for _ in queries]
        for i, (query, selected_filters) in enumerate(zip(queries, selected_per_query)):
            if not selected_filters:
                logger.info("Two-stage | query=%r | clause=null (no filters selected)", query)
                continue
            catalog_json = _format_catalog_json(self.filter_catalog, selected_filters)
            raw_where = self._plan_where(
                query=query,
                filter_catalog=catalog_json,
                template="",
            )
            clause = _parse_json(raw_where, default=None)
            selected_catalog = {name: self.filter_catalog[name] for name in selected_filters}
            results[i] = _normalize_where(clause, selected_catalog)
            logger.info(
                "Two-stage | query=%r | clause=%s",
                query,
                json.dumps(results[i]) if results[i] else "null",
            )

        return results
