indexing:
  embedding_model: "BAAI/bge-small-en-v1.5"
  index_first_512: True       
  chunk_size: 512
  overlap: 80
  batch_size: 512
  
  chroma:
    persist_dir: "./chroma_quest"       
    collection: "quest_documents"

data:
  document_path: /orcd/home/002/joycequ/quest_data/documents.jsonl
  queries_file: data/train_subset1.jsonl

decomposition:
  top_k: 100

retrieval:
  top_k: 100