from __future__ import annotations

import json
import textwrap

from pydantic import BaseModel

from carnot.data.dataset import Dataset
from carnot.utils.hash_helpers import hash_for_id


class LogicalOperator:
    """
    A logical operator is an operator that operates on Sets.

    Right now it can be one of:
    - BaseScan (scans data from a root Dataset)
    - ContextScan (loads the context for a root Dataset)
    - FilteredScan (scans input Set and applies filter)
    - MapScan (scans input Set and converts it to new Schema)
    - LimitScan (scans up to N records from a Set)
    - Aggregate (applies an aggregation on the Set)
    - TopK (fetches documents from a provided input for a given query)
    - Map (applies a function to each record in the Set without adding any new columns)
    - ComputeOperator (executes a computation described in natural language)
    - SearchOperator (executes a search query on the input Context)

    Every logical operator must declare the get_logical_id_params() and get_logical_op_params() methods,
    which return dictionaries of parameters that are used to compute the logical op id and to implement
    the logical operator (respectively).
    """

    def __init__(
        self,
        output_schema: type[BaseModel],
        input_schema: type[BaseModel] | None = None,
        depends_on: list[str] | None = None,
    ):
        # TODO: can we eliminate input_schema?
        self.output_schema = output_schema
        self.input_schema = input_schema
        self.depends_on = [] if depends_on is None else sorted(depends_on)
        self.logical_op_id: str | None = None
        self.unique_logical_op_id: str | None = None

        # compute the fields generated by this logical operator
        input_field_names = list(self.input_schema.model_fields) if self.input_schema is not None else []
        self.generated_fields = sorted(
            [field_name for field_name in self.output_schema.model_fields if field_name not in input_field_names]
        )

    def desc(self) -> str:
        raise NotImplementedError("Abstract method")

    def __str__(self) -> str:
        raise NotImplementedError("Abstract method")

    def __eq__(self, other) -> bool:
        all_id_params_match = all(value == getattr(other, key) for key, value in self.get_logical_id_params().items())
        return isinstance(other, self.__class__) and all_id_params_match

    def copy(self) -> LogicalOperator:
        logical_op_copy = self.__class__(**self.get_logical_op_params())
        logical_op_copy.logical_op_id = self.logical_op_id
        logical_op_copy.unique_logical_op_id = self.unique_logical_op_id
        return logical_op_copy

    def logical_op_name(self) -> str:
        """Name of the logical operator."""
        return str(self.__class__.__name__)

    def get_unique_logical_op_id(self) -> str:
        """
        Get the unique logical operator id for this logical operator.
        """
        return self.unique_logical_op_id

    def set_unique_logical_op_id(self, unique_logical_op_id: str) -> None:
        """
        Set the unique logical operator id for this logical operator.
        This is used to uniquely identify the logical operator in the query plan.
        """
        self.unique_logical_op_id = unique_logical_op_id

    def get_logical_id_params(self) -> dict:
        """
        Returns a dictionary mapping of logical operator parameters which are relevant
        for computing the logical operator id.

        NOTE: Should be overriden by subclasses to include class-specific parameters.
        NOTE: input_schema and output_schema are not included in the id params because
              they depend on how the Optimizer orders operations.
        """
        # TODO: should we use `generated_fields` after getting rid of them in PhysicalOperator?
        return {"generated_fields": self.generated_fields}

    def get_logical_op_params(self) -> dict:
        """
        Returns a dictionary mapping of logical operator parameters which may be used to
        implement a physical operator associated with this logical operation.

        NOTE: Should be overriden by subclasses to include class-specific parameters.
        """
        return {
            "input_schema": self.input_schema,
            "output_schema": self.output_schema,
            "depends_on": self.depends_on,
        }

    def get_logical_op_id(self):
        """
        TODO: turn this into a property?

        NOTE: We do not call this in the __init__() method as subclasses may set parameters
              returned by self.get_logical_op_params() after they call to super().__init__().
        """
        # return self.logical_op_id if we've computed it before
        if self.logical_op_id is not None:
            return self.logical_op_id

        # get op name and op parameters which are relevant for computing the id
        logical_op_name = self.logical_op_name()
        logical_id_params = self.get_logical_id_params()
        logical_id_params = {k: str(v) for k, v in logical_id_params.items()}

        # compute, set, and return the op_id
        hash_str = json.dumps({"logical_op_name": logical_op_name, **logical_id_params}, sort_keys=True)
        self.logical_op_id = hash_for_id(hash_str)

        return self.logical_op_id

    def get_generated_fields(self) -> list[str]:
        """Returns the names of the fields generated by this logical operator."""
        return self.generated_fields

    def __hash__(self):
        if not self.logical_op_id:
            raise ValueError("logical_op_id not set, unable to hash")
        return int(self.logical_op_id, 16)


class Aggregate(LogicalOperator):
    """
    Aggregate is a logical operator that applies an aggregation to the input set and yields a single result.
    This is a base class that has to be further specialized to implement specific aggregation functions.
    """

    def __init__(
        self,
        agg_func: str,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.agg_func = agg_func

    @staticmethod
    def desc() -> str:
        return textwrap.dedent(
            """
            Aggregate Operator:
                Description: Applies one or more semantic aggregations to the entire input dataset.
                    Useful for summarization or finding extremal input(s). For example, finding the most negative reviews
                    in a set of product reviews, or summarizing a set of legal contracts. Takes in a `task` string that
                    describes the aggregation(s) to be performed in natural language, as well as a list of the aggregation
                    fields to be computed (provide the "name", "type", and "description", and always set `"func": "sem_agg"`).
                Syntax: ds.sem_aggregate(agg_fields: list[dict])
                Example: ds.sem_aggregate(
                  task="Summarize the legal contracts and identify the most problematic clauses.",
                  agg_fields=[
                    {"name": "summary", "type": str, "description": "A concise summary of the legal contracts", "func": "sem_agg"},
                    {"name": "worst_clauses", "type": list[str], "description": "A list of the most problematic clauses in the legal contracts", "func": "sem_agg"},
                  ],
                )
                Example: ds.sem_aggregate(
                  task="Identify the most negative product review.",
                  agg_fields=[
                    {"name": "most_negative_review", "type": str, "description": "The text of the most negative product review", "func": "sem_agg"},
                  ],
                )

            GroupBy Operator:
                Description: Groups the input set by specified columns and applies an aggregation function to each group.
                    The supported aggregation `func`s are: "min", "max", "mean", "count", and "sum".
                    You may compute a semantic aggregation by specifying `func` as "sem_agg".
                    The `agg_fields` must exist in the dataset already, but the `gby_fields` can be new fields derived from existing fields.
                Syntax: ds.sem_groupby(gby_fields: list[dict], agg_fields: list[dict])
                Example (semantic group, relational aggregate):
                  # assume input has a "review_text" column which can be used to compute "sentiment"
                  ds.sem_groupby(
                    gby_fields=[{"name": "sentiment", "type": str, "description": "the sentiment (POSITIVE or NEGATIVE) of the movie review"}],
                    agg_fields=[{"name": "count", "type": int, "description": "the count of each review sentiment", "func": "count"}],
                  )
                Example (semantic group, semantic aggregate):
                  # assume the same example as before
                  ds.sem_groupby(
                    gby_fields=[{"name": "sentiment", "type": str, "description": "the sentiment (POSITIVE or NEGATIVE) of the movie review"}],
                    agg_fields=[
                      {"name": "count", "type": int, "description": "the count of each review sentiment", "func": "count"}
                      {"name": "summary", "type": str, "description": "a concise summary of the reviews for each sentiment", "func": "sem_agg"},
                    ],
                  )
                Example (relational group, relational aggregate):
                  # assume we have a "sales" dataset with "region", "product_category", and "amount" columns
                  ds.sem_groupby(
                    gby_fields=[
                      {"name": "region", "type": str, "description": "the sales region"},
                      {"name": "product_category", "type": str, "description": "the product category"},
                    ],
                    agg_fields=[
                      {"name": "total_sales", "type": float, "description": "the total sales amount for the region and product category", "func": "sum"},
                    ],
                  )
            """
        )

    def __str__(self):
        return f"{self.__class__.__name__}(function: {str(self.agg_func.value)})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"agg_func": self.agg_func, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "agg_func": self.agg_func,
            **logical_op_params,
        }

        return logical_op_params


class BaseScan(LogicalOperator):
    """A BaseScan is a logical operator that represents a scan of a particular root Dataset."""

    def __init__(self, datasource: Dataset, output_schema: type[BaseModel], *args, **kwargs):
        super().__init__(*args, output_schema=output_schema, **kwargs)
        self.datasource = datasource

    @staticmethod
    def desc() -> str:
        # TODO
        return ""

    def __str__(self):
        return f"BaseScan({self.datasource},{self.output_schema})"

    def __eq__(self, other) -> bool:
        return (
            isinstance(other, BaseScan)
            and self.input_schema == other.input_schema
            and self.output_schema == other.output_schema
            and self.datasource == other.datasource
        )

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {
            "id": self.datasource.id,
            **logical_id_params,
        }

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {"datasource": self.datasource, **logical_op_params}

        return logical_op_params


class Code(LogicalOperator):
    """A Code is a logical operator that represents a code operation on the input Dataset."""

    def __init__(self, task: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.task = task

    @staticmethod
    def desc() -> str:
        return textwrap.dedent(
            """
            Code Operator:
                Description: Use a coding agent to perform computation over structured data based on a natural language task description.
                Syntax: ds.write_code(task: str)
                Example: ds.write_code(task="Compute the total revenue for each product category in the sales dataset.")
            """
        )

    def __str__(self):
        return f"Code(task: {self.task})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"task": self.task, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {"task": self.task, **logical_op_params}

        return logical_op_params

class MapScan(LogicalOperator):
    """A MapScan is a logical operator that represents a scan of a particular input Dataset, with a map operation applied."""

    def __init__(
        self,
        desc: str | None = None,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self._desc = desc

    @staticmethod
    def desc() -> str:
        return textwrap.dedent(
            """
            Map Operator:
                Description: Executes a semantic map operation by applying an LLM to each record in the input set to compute an output field.
                Syntax: ds.sem_map(field: str, type: type, description: str)
                Example: ds.sem_map(field="summary", type=str, description="A concise summary of the legal contract")

            Flat Map Operator:
                Description: Executes a semantic flat map operation by applying an LLM to each record in the input set to compute multiple output records per input record.
                Syntax: ds.sem_flat_map(field: str, type: type, description: str)
                Example: ds.sem_flat_map(field="key_points", type=str, description="Key points extracted from the legal contract")
            """
        )

    def __str__(self):
        return f"MapScan({self.input_schema} -> {str(self.output_schema)})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {
            "desc": self._desc,
            **logical_id_params,
        }

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "desc": self._desc,
            **logical_op_params,
        }

        return logical_op_params


class Distinct(LogicalOperator):
    def __init__(self, distinct_cols: list[str] | None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # if distinct_cols is not None, check that all columns are in the input schema
        if distinct_cols is not None:
            for col in distinct_cols:
                assert col in self.input_schema.model_fields, f"Column {col} not found in input schema {self.input_schema} for Distinct operator"

        # store the list of distinct columns, sorted
        self.distinct_cols = (
            sorted([field_name for field_name in self.input_schema.model_fields])
            if distinct_cols is None
            else sorted(distinct_cols)
        )

    @staticmethod
    def desc() -> str:
        # TODO
        return ""

    def __str__(self):
        return f"Distinct({self.distinct_cols})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"distinct_cols": self.distinct_cols, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "distinct_cols": self.distinct_cols,
            **logical_op_params,
        }

        return logical_op_params


class FilteredScan(LogicalOperator):
    """A FilteredScan is a logical operator that represents a scan of a particular input Dataset, with filters applied."""

    def __init__(
        self,
        filter: str,
        desc: str | None = None,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.filter = filter
        self._desc = desc

    @staticmethod
    def desc() -> str:
        return textwrap.dedent(
            """
            Filter Operator:
                Description: Applies a semantic filter to the input set based on a provided natural language condition.
                Syntax: ds.sem_filter(condition: str)
                Example: ds.sem_filter("The image contains a sunset over the mountains")
            """
        )

    def __str__(self):
        return f"FilteredScan({str(self.output_schema)}, {str(self.filter)})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {
            "filter": self.filter,
            "desc": self._desc,
            **logical_id_params,
        }

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "filter": self.filter,
            "desc": self._desc,
            **logical_op_params,
        }

        return logical_op_params


class JoinOp(LogicalOperator):
    def __init__(self, condition: str, desc: str | None = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.condition = condition
        self._desc = desc

    @staticmethod
    def desc():
        return textwrap.dedent(
            """
            Join Operator:
                Description: Semantically joins two input sets based on a provided natural language condition.
                Syntax: ds.sem_join(other_ds: Dataset, condition: str)
                Example: ds.sem_join(other_ds=orders_ds, condition="customer_id matches id in the order PDF")
            """
        )

    def __str__(self):
        return f"Join(condition={self.condition})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"condition": self.condition, "desc": self._desc, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "condition": self.condition,
            "desc": self._desc,
            **logical_op_params,
        }

        return logical_op_params


class Limit(LogicalOperator):
    def __init__(self, limit: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.limit = limit

    @staticmethod
    def desc() -> str:
        return textwrap.dedent(
            """
            Limit Operator:
                Description: return the first N records from the input set. Useful for limiting the number of records returned or for debugging.
                Syntax: ds.limit(n: int)
                Example: ds.limit(n=10)
            """
        )

    def __str__(self):
        return f"Limit({str(self.input_schema)}, {str(self.output_schema)})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"limit": self.limit, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "limit": self.limit,
            **logical_op_params,
        }

        return logical_op_params


class Project(LogicalOperator):
    def __init__(self, project_cols: list[str], *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_cols = project_cols

    @staticmethod
    def desc() -> str:
        # TODO
        return ""

    def __str__(self):
        return f"Project({self.input_schema}, {self.project_cols})"

    def get_logical_id_params(self) -> dict:
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {"project_cols": self.project_cols, **logical_id_params}

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "project_cols": self.project_cols,
            **logical_op_params,
        }

        return logical_op_params


class TopK(LogicalOperator):
    """A TopK is a logical operator that represents a semantic search over the input dataset for the top-k most relevant items."""

    def __init__(
        self,
        index,
        search_func,
        search_attr,
        output_attrs,
        k,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.index = index
        self.search_func = search_func
        self.search_attr = search_attr
        self.output_attrs = output_attrs
        self.k = k

    @staticmethod
    def desc():
        return textwrap.dedent(
            """
            Top-K Operator:
                Description: Searches for the top-k most semantically relevant items to a given search string.
                Syntax: ds.sem_topk(search_str: str, k: int)
                Example: ds.sem_topk(search_str="order contains self-care products", k=5)
            """
        )

    def __str__(self):
        return f"TopK({self.input_schema} -> {str(self.output_schema)})"

    def get_logical_id_params(self) -> dict:
        # NOTE: if we allow optimization over index, then we will need to include it in the id params
        # NOTE: ^if we do this, we should probably make a wrapper around the index object to ensure that
        #       it can be serialized as a string properly
        logical_id_params = super().get_logical_id_params()
        logical_id_params = {
            "search_attr": self.search_attr,
            "output_attrs": self.output_attrs,
            "k": self.k,
            **logical_id_params,
        }

        return logical_id_params

    def get_logical_op_params(self) -> dict:
        logical_op_params = super().get_logical_op_params()
        logical_op_params = {
            "index": self.index,
            "search_func": self.search_func,
            "search_attr": self.search_attr,
            "output_attrs": self.output_attrs,
            "k": self.k,
            **logical_op_params,
        }

        return logical_op_params
