apiVersion: v1
kind: Service
metadata:
  name: carnot-backend
  namespace: {{ .Values.env }}
  labels:
    app.kubernetes.io/name: carnot
    app.kubernetes.io/instance: {{ .Values.env }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: carnot-{{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: carnot
    app.kubernetes.io/instance: {{ .Values.env }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
