from typing import Any

from pydantic import BaseModel

from carnot.agents.memory import ConversationAgentStep, ConversationUserStep, MemoryStep


class Message(BaseModel):
    role: str
    content: str
    type: str | None = None


class Conversation:
    """
    Manages conversation history between a user and the Carnot system.
    
    Attributes:
        user_id: Identifier for the user
        session_id: Identifier for the conversation session
        title: Title of the conversation
        dataset_ids: List of dataset IDs used in this conversation
        messages: List of messages exchanged (dicts with 'role', 'content', and optional 'type' keys)
    """
    def __init__(
        self, 
        user_id: str, 
        session_id: str, 
        title: str, 
        dataset_ids: list[str], 
        messages: list[dict[str, Any]] | None = None
    ):
        self.user_id = user_id
        self.session_id = session_id
        self.title = title
        self.dataset_ids = dataset_ids
        self.messages = messages or []

    def add_message(self, role: str, content: str, message_type: str | None = None):
        """
        Add a message to the conversation history.
        
        Args:
            role: The role of the message sender ('user' or 'agent')
            content: The content of the message
            message_type: Optional type identifier (e.g., 'natural-language-plan', 'logical-plan')
        """
        message = {"role": role, "content": content}
        if message_type:
            message["type"] = message_type
        self.messages.append(message)

    def to_memory_steps(self) -> list[MemoryStep]:
        """
        Convert conversation messages to a list of MemoryStep objects.
        
        This method converts the conversation history into MemoryStep objects that can be
        used in agent memory. User messages become ConversationUserStep objects, and agent
        messages become ConversationAgentStep objects.
        
        Returns:
            List of MemoryStep objects representing the conversation
        """
        memory_steps = []
        for msg in self.messages:
            role = msg.get("role")
            content = msg.get("content", "")
            msg_type = msg.get("type")
            
            if role == "user":
                memory_steps.append(ConversationUserStep(content=content))
            elif role == "agent":
                memory_steps.append(ConversationAgentStep(content=content, message_type=msg_type))
        
        return memory_steps

    def get_latest_user_message(self) -> ConversationUserStep | None:
        """
        Get the most recent message from the user.
        
        Returns:
            Dictionary containing the latest user message, or None if no user messages exist
        """
        for msg in reversed(self.messages):
            if msg["role"] == "user":
                return ConversationUserStep(content=msg["content"])
        return None

    def get_latest_agent_plan(self, plan_type: str = "natural-language-plan") -> ConversationAgentStep | None:
        """
        Get the most recent plan generated by the agent.
        
        Args:
            plan_type: Type of plan to retrieve ('natural-language-plan' or 'logical-plan')
            
        Returns:
            Dictionary containing the latest plan of the specified type, or None if not found
        """
        for msg in reversed(self.messages):
            if msg["role"] == "agent" and msg["type"] == plan_type:
                return ConversationAgentStep(content=msg["content"], message_type=plan_type)
        return None

    def to_dict_list(self) -> list[dict[str, Any]]:
        """
        Convert conversation messages to a list of dictionaries.
        
        Returns:
            List of message dictionaries suitable for serialization
        """
        return self.messages.copy()

    def condense(self, query: str) -> str:
        """
        Condense the conversation history relevant to the query.
        
        Args:
            query: The query to condense the conversation around
            
        Returns:
            A condensed string representation of the conversation
        """
        # TODO: Implement intelligent conversation condensation
        # For now, return a simple concatenation
        condensed = []
        for msg in self.messages:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")
            msg_type = msg.get("type", "")
            type_str = f" ({msg_type})" if msg_type else ""
            condensed.append(f"{role}{type_str}: {content}")
        
        return "\n\n".join(condensed)
