"""Centralized configuration for experiments."""

from __future__ import annotations

import uuid
import yaml
from dataclasses import dataclass, field
from typing import cast, Literal
from omegaconf import DictConfig, OmegaConf
from qatfd.constants import BROWSECOMP_PLUS, FINANCE_BENCH, FRESHSTACK, OFFICE_QA, OFFICE_QA_SYNTH, QAMPARI, TREC_BIOGEN
from skunk.config import AgentConfig, SearchAgentConfig, StorageConfig

# ---------------------------------------------------------------------------
# A SystemConfig in QATFD is an AgentConfig
# ---------------------------------------------------------------------------

@dataclass
class RAGLLMConfig(AgentConfig):
    # number of chunks for the vector search to return
    top_k: int | None = None

    def __post_init__(self) -> None:
        if self.top_k is None:
            raise ValueError(
                "RAGLLMConfig.top_k is unset (null); set it explicitly, e.g. "
                "`systems.top_k=20` on the command line."
            )

@dataclass(kw_only=True)
class CodexConfig(AgentConfig):
    # path to the root directory for the Codex agent (config.toml, sessions, and state)
    codex_home: str
    # path to the directory containing the per-question scratch directories; should be distinct from codex_home
    codex_scratch_dir: str
    # path to the example answer schema json file
    codex_answer_schema_file: str
    # list of tools the Codex agent may use
    enabled_tools: list[str]
    # URL of the MCP server
    mcp_url: str
    # # overrides on the hydra configuration
    # extra_overrides: dict
    # mode in which we run the CodexSystem; differs from ExperimentConfig.run_mode
    # because this defines whether each question is processed in isolation or in
    # sequence such that Codex can attend to previous queries to answer future ones
    mode: Literal["isolated", "sequential"] = "isolated"

# ---------------------------------------------------------------------------
# General experiment configuration
# ---------------------------------------------------------------------------


@dataclass
class ExperimentConfig:
    # the benchmark split to run (dev|test)
    split: Literal["dev", "test"] = "dev"
    # number of questions to run
    sample: int | None = None
    # RNG seed for `sample` selection; set it to draw the same subset across systems (null = nondeterministic)
    seed: int | None = None
    # specific qids to run (overrides split/sample)
    qids: list[str] | None = None
    # question-level concurrency
    workers: int = 32
    # label prefix for the run dir
    run_name: str = ""
    # whether to stream logs to the console (in addition to files)
    console: bool = False
    # resume an interrupted run: path to its existing run dir (the one holding results.jsonl /
    # traces). Questions already recorded in results.jsonl are skipped; the rest are (re)run into
    # the same dir. Reuse the SAME benchmark/system/split/sample/seed so the question set matches.
    resume_dir: str | None = None
    # the mode to run the experiment questions in (parallel|sequential|all)
    run_mode: Literal["parallel", "sequential", "all"] = "parallel"
    # the session_id (for Codex to use for experiment tracking)
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    @classmethod
    def from_yaml(cls, path: str) -> ExperimentConfig:
        with open(path) as f:
            data = yaml.safe_load(f)
        return cls(**data)


# --------------------------------------------------------------------------------
# Benchmark-specific configuration
# --------------------------------------------------------------------------------


@dataclass
class BenchmarkConfig:
    # name of the benchmark
    name: str
    # storage for the benchmark's data
    storage: StorageConfig
    # path (under qatfd/benchmarks/) to the dev/test split JSON — {"dev": [qids], "test": [qids]}. The runner selects
    # `experiments.split` from these lists (dev is explicit, not test's complement). null => no split
    # (dev = everything, test = empty). Generated by scripts/make_splits.py.
    splits_path: str | None
    # path to the root directory for the Codex agent (config.toml, sessions, and state)
    codex_home: str
    # path to the directory containing the per-question scratch directories; should be distinct from codex_home
    codex_scratch_dir: str
    # path to the example answer schema json file
    codex_answer_schema_file: str
    # url for mcp server
    mcp_url: str

    @classmethod
    def from_yaml(cls, path: str) -> BenchmarkConfig:
        with open(path) as f:
            data = yaml.safe_load(f)
        return cls(**data)


@dataclass
class OfficeQAConfig(BenchmarkConfig):
    # path to the benchmark questions and answers
    csv_path: str
    # document map containing clean page text
    clean_page_map_path: str


@dataclass
class OfficeQASynthConfig(OfficeQAConfig):
    # path (under qatfd/benchmarks/, or absolute) to the synthetic qa_pairs.json
    qa_pairs_path: str


@dataclass
class BrowseCompPlusConfig(BenchmarkConfig):
    # file containing questions for BrowseComp-Plus
    bcp_questions: str
    # glob for metadata files containing doc_id -> source info (e.g. URL) for BrowseComp-Plus documents
    bcp_metadata_glob: str
    # the llm to use for judging system outputs on BrowseComp-Plus
    judge_model: str


@dataclass
class TrecBiogenConfig(BenchmarkConfig):
    # 2025 BioGen Task A JSON: 40 questions + expert reference answers w/cited PMIDs. Task A's
    # expert answers are the 2024-edition answers re-released against the 2025 corpus.
    task_a_path: str
    # the llm used to judge nugget-completion (gold nuggets vs the system answer, KARL D.1 prompt)
    judge_model: str
    # JSON of official gold nuggets keyed by qa_id (organizer/BioACE `baseline_labels.json`: a
    # list of {meta_data.qa_id, answer:[{nuggets:[...]}]}, flattened per question).
    # NOTE: the official nuggets are finer-grained (~24.6/q) than KARL's consolidated set (~7.1/q),
    # so the absolute nugget completion number is NOT directly comparable to KARL's reported 85.0.
    nuggets_path: str
    # weight given to a `partial_support` nugget in the recall score (full support = 1.0).
    partial_credit: float = 0.0
    # If >1, the 26.8M-abstract corpus is split across N per-rank Chroma collections named
    # f"{collection_name}_r{i}", each built in its OWN chroma dir (its own chroma.sqlite3). Separate
    # dirs are essential at build time: collections in ONE dir share one chroma.sqlite3, so it still
    # hits chromadb 1.5.x's ~24M-row metadata-segment scale wall. At read time the benchmark opens all
    # N shard collections and merges query/get across them (MergedCollection). 1 => single collection.
    chroma_server_num_shards: int = 1
    # Optional per-shard chroma SERVER ports (len == chroma_server_num_shards): shard i is served by a warm
    # chroma server at (chroma_server_host, ports[i]) over that shard's dir. The benchmark connects via
    # HttpClient per shard and queries them in PARALLEL — HNSW stays resident across runs (no cold
    # load). When null, all N shard collections are opened by name from the single (chroma_server_host,
    # chroma_server_port) server. Launch servers via scripts/run_chroma_server.sh.
    chroma_server_shard_ports: list[int] | None = None


@dataclass
class QampariConfig(BenchmarkConfig):
    # QAMPARI test JSONL (`test_data.jsonl`): the 1000-question KARL eval set over Wikipedia. Each
    # record is (qid, question_text, answer_list[]) where every answer carries `answer_text`,
    # `aliases`, and `proof[]` (each proof has `found_in_url` = the supporting Wikipedia article).
    # This is the held-out TEST split (all 1000 qids); run it with experiments.split=test.
    questions_path: str
    # the llm used by the nugget-completion judge (each gold answer entity is one nugget; the answer
    # is graded by entity recall, mirroring KARL's nugget-based completion for QAMPARI). The passage
    # text + article title are served from the Chroma collection at eval time (the full ~25.9M-chunk
    # corpus is too large for an in-RAM doc map), so no metadata-glob config is needed.
    judge_model: str
    # dev JSONL: 50 questions sampled (seed 0) from QAMPARI's train_data — DISJOINT from the test set
    # (which is the full KARL 1000, so dev never leaks into test). Loaded ALONGSIDE questions_path so
    # experiments.split=dev resolves with no per-run override; both splits share the one Wikipedia
    # index (the split is purely at the question level). Same record schema as questions_path.
    # Generated by scripts/make_splits.py. null => no dev extract (the dev split finds no questions).
    dev_questions_path: str | None = None
    # weight given to a `partial_support` nugget in the recall score (full support = 1.0).
    partial_credit: float = 0.0


@dataclass
class FinanceBenchConfig(BenchmarkConfig):
    # FinanceBench open-source JSONL: 150 questions over SEC filings (financebench_id / question /
    # answer / evidence[{doc_name, evidence_page_num, ...}]).
    questions_path: str
    # glob for the embedding-job metadata files (metadata_rank*.json: unique_element_id ->
    # {doc_name, page_num, page_key, cleaned, element_id}), used to rebuild the page-text doc map.
    fb_metadata_glob: str
    # the llm used to judge answer correctness (single-nugget YES/NO judge, KARL-style; see judge.py).
    judge_model: str


@dataclass
class FreshstackConfig(BenchmarkConfig):
    # the llm used by the nugget-completion judge (each gold nugget is one GPT-4o decompositional
    # fact; the answer is graded by nugget recall, mirroring KARL's nugget-based completion).
    judge_model: str
    # FreshStack topic = which (corpus, queries) pair to run. Each topic has its OWN corpus and so
    # its OWN Chroma collection (unlike QAMPARI's shared index): `langchain` is KARL's FreshStack and
    # the held-out TEST set (203 q / 49,514 docs); `laravel` is the closest-sized DEV set (184 q /
    # 52,351 docs). To run dev, override `benchmarks.topic=laravel` — it re-derives the data paths and
    # collection below. (Others: angular, godot, yolo.)
    topic: str = "langchain"
    # base dir under qatfd/benchmarks/ holding each topic's data at `{data_dir}/{topic}/{corpus,queries}.jsonl`.
    data_dir: str = "freshstack"
    # FreshStack queries JSONL; null => derived from topic as `{data_dir}/{topic}/queries.jsonl`. Each
    # record is (query_id, query_title, query_text, nuggets[]) where every nugget carries `text`
    # (a decompositional fact) and `relevant_corpus_ids` (the supporting corpus doc ids).
    questions_path: str | None = None
    # FreshStack corpus JSONL; null => derived from topic as `{data_dir}/{topic}/corpus.jsonl`. Each
    # record is (_id, text, metadata); read directly into the doc map (_id -> text) — the corpus is
    # small enough to hold in RAM and the file is the source of truth for the embedded text.
    corpus_path: str | None = None
    # weight given to a `partial_support` nugget in the recall score (full support = 1.0).
    partial_credit: float = 0.0


# ---------------------------------------------------------------------------
# configuration factories
# ---------------------------------------------------------------------------


def benchmark_config_factory(cfg: DictConfig) -> BenchmarkConfig:
    bench_cfg = cast(dict, OmegaConf.to_container(cfg.benchmarks, resolve=True))
    bench_cfg["storage"] = StorageConfig(
        collection_name=bench_cfg.pop("collection_name"),
        chroma_server_host=bench_cfg.pop("chroma_server_host"),
        chroma_server_port=bench_cfg.pop("chroma_server_port"),
        pdf_dir=bench_cfg.pop("pdf_dir", None),
    )
    if bench_cfg["name"] == OFFICE_QA:
        return OfficeQAConfig(**bench_cfg)
    elif bench_cfg["name"] == OFFICE_QA_SYNTH:
        return OfficeQASynthConfig(**bench_cfg)
    elif bench_cfg["name"] == BROWSECOMP_PLUS:
        return BrowseCompPlusConfig(**bench_cfg)
    elif bench_cfg["name"] == TREC_BIOGEN:
        return TrecBiogenConfig(**bench_cfg)
    elif bench_cfg["name"] == FINANCE_BENCH:
        return FinanceBenchConfig(**bench_cfg)
    elif bench_cfg["name"] == QAMPARI:
        return QampariConfig(**bench_cfg)
    elif bench_cfg["name"] == FRESHSTACK:
        return FreshstackConfig(**bench_cfg)
    else:
        raise ValueError(f"unknown benchmark {bench_cfg['name']!r}")


def system_config_factory(cfg: DictConfig) -> tuple[AgentConfig | None, AgentConfig | None, AgentConfig | None]:
    system_cfg = cast(dict, OmegaConf.to_container(cfg.systems, resolve=True))
    if system_cfg["name"] == "rag_llm":
        retrieve_cfg = RAGLLMConfig(**system_cfg["retrieve"])
        compute_cfg = AgentConfig(**system_cfg["compute"])
        return retrieve_cfg, compute_cfg, None
    elif system_cfg["name"] == "search_agent":
        retrieve_cfg = SearchAgentConfig(**system_cfg["retrieve"])
        compute_cfg = AgentConfig(**system_cfg["compute"])
        return retrieve_cfg, compute_cfg, None
    elif system_cfg["name"] == "codex":
        codex_cfg = CodexConfig(**system_cfg)
        return None, None, codex_cfg
    else:
        raise ValueError(f"unknown system {system_cfg['name']!r}")
