# syntax=docker/dockerfile:1
FROM python:3.12-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY ./backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8000
COPY ./backend .
CMD ["uvicorn", "app.main:app", "--reload", "--port", "8000", ">", "backend.log", "2>&1"]
