# syntax=docker/dockerfile:1
# Stage 1 — Build Vite frontend
FROM node:18 AS builder
WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

# Stage 2 — Serve with NGINX
FROM nginx:alpine

# Copy built frontend to Nginx html directory
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
