name: Deploy to AWS

on:
  push:
    branches:
    - main
    - wl-prod
    - wm-prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.5
          terraform_wrapper: false

      - name: Determine subdomain
        id: subdomain
        run: |
          if [[ "${GITHUB_REF_NAME}" == "wl-prod" ]]; then
            echo "SUBDOMAIN=${{ secrets.WL_PROD }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "wm-prod" ]]; then
            echo "SUBDOMAIN=${{ secrets.WM_PROD }}" >> $GITHUB_ENV
          else
            echo "SUBDOMAIN=dev" >> $GITHUB_ENV
          fi

      - name: Determine Priority priority_offset
        id: priority_offset
        run: |
          if [[ "${GITHUB_REF_NAME}" == "wl-prod" ]]; then
            echo "PRIORITY_OFFSET=100" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "wm-prod" ]]; then
            echo "PRIORITY_OFFSET=200" >> $GITHUB_ENV
          else
            echo "PRIORITY_OFFSET=0" >> $GITHUB_ENV
          fi

      - name: Determine environment
        id: environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "wl-prod" ]]; then
            echo "ENV_NAME=wl-prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "wm-prod" ]]; then
            echo "ENV_NAME=wm-prod" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi
          echo "ENV_NAME=${ENV_NAME}"
          echo "SUBDOMAIN=${SUBDOMAIN}"
          echo "PRIORITY_OFFSET=${PRIORITY_OFFSET}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::422297141788:role/CarnotGithubRole
          aws-region: us-east-1

      - name: Write Deployer Key to Files
        env:
          CARNOT_DEPLOY_KEY: ${{ secrets.CARNOT_DEPLOY_KEY }}
        run: |
          echo "$CARNOT_DEPLOY_KEY" > deployer_key.pem
          chmod 400 deployer_key.pem

      ######################################################################
      # STEP 1 — DEPLOY GLOBAL TERRAFORM
      ######################################################################
      - name: Terraform Init (Global)
        working-directory: deploy/terraform/global
        id: init-global
        run: terraform init

      - name: Terraform Validate (Global)
        working-directory: deploy/terraform/global
        id: validate-global
        run: terraform validate

      - name: Write Global vars.tfvars
        working-directory: deploy/terraform/global
        run: |
          cat > global-vars.tfvars <<EOF
          auth0_custom_domain = "${{ secrets.AUTH0_CUSTOM_DOMAIN }}"
          auth0_cname_target = "${{ secrets.AUTH0_CNAME_TARGET }}"
          EOF

      - name: Terraform Apply (Global)
        working-directory: deploy/terraform/global
        id: apply-global
        run: |
          terraform apply -var-file="global-vars.tfvars" -auto-approve
      
      - name: Get Homepage EC2 Public IP
        working-directory: deploy/terraform/global
        id: homepage-ip
        run: |
          homepage_public_ip=$(terraform output -raw homepage_public_ip)
          echo "HOMEPAGE_PUBLIC_IP=$homepage_public_ip" >> $GITHUB_ENV

      - name: Start NGINX on Homepage EC2
        env:
          CARNOT_DEPLOY_KEY: ${{ secrets.CARNOT_DEPLOY_KEY }}
        run: |
          echo "Copying homepage files to $HOMEPAGE_PUBLIC_IP"
          
          # copy index.html to EC2; sleep first to wait for it to be ready to accept SSH connections
          sleep 5
          scp -o StrictHostKeyChecking=no -i deployer_key.pem app/index.html ubuntu@$HOMEPAGE_PUBLIC_IP:~/

          # Copy index.html to the NGINX default location inside the container's volume mount and (re)start container
          ssh -o StrictHostKeyChecking=no -i deployer_key.pem ubuntu@$HOMEPAGE_PUBLIC_IP "
            sudo docker start carnot-homepage-nginx
            sleep 3
            sudo docker cp index.html carnot-homepage-nginx:/usr/share/nginx/html/index.html
            rm index.html
            sudo docker restart carnot-homepage-nginx
          "

      ######################################################################
      # STEP 2 — DEPLOY ENVIRONMENT TERRAFORM
      ######################################################################

      - name: Terraform Init (env)
        working-directory: deploy/terraform/env
        run: terraform init -backend-config="backend-config/backend.hcl"

      - name: Ensure Terraform Workspace Exists
        working-directory: deploy/terraform/env
        run: |
          terraform workspace list || true
          terraform workspace new "$ENV_NAME" 2>/dev/null || true

      - name: Select Workspace
        working-directory: deploy/terraform/env
        run: terraform workspace select "$ENV_NAME"
      
      - name: Terraform Validate (env)
        working-directory: deploy/terraform/env
        run: terraform validate

      - name: Write Env vars.tfvars
        working-directory: deploy/terraform/env
        run: |
          cat > env-vars.tfvars <<EOF
          subdomain = "${SUBDOMAIN}"
          priority_offset = "${PRIORITY_OFFSET}"
          EOF

      - name: Terraform Apply (env)
        working-directory: deploy/terraform/env
        run: |
          terraform apply -var-file="env-vars.tfvars" -auto-approve

      - name: Store EC2 Public IP
        working-directory: deploy/terraform/env
        id: ec2-ip
        run: |
          ec2_public_ip=$(terraform output -raw ec2_public_ip)
          echo "EC2_PUBLIC_IP=$ec2_public_ip" >> $GITHUB_ENV

      ######################################################################
      # STEP 3 — BUILD & DEPLOY APPLICATION
      ######################################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Images to Docker Hub
        run: |
          # copy relevant source files to build context
          cp -r app/frontend deploy/compose/frontend
          cp -r app/backend deploy/compose/backend
          cp -r src deploy/compose/src
          cp pyproject.toml deploy/compose/pyproject.toml
          cp README.md deploy/compose/README.md

          # navigate to build context
          cd deploy/compose

          # set environment variables for build arguments;
          export DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          export ENV_NAME=${ENV_NAME}
          export VITE_AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          export VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_CUSTOM_DOMAIN }}
          export VITE_API_BASE_URL="https://${SUBDOMAIN}.carnot-research.org/api"
          if [[ "${GITHUB_REF_NAME}" == "wl-prod" ]]; then
            export VITE_AUTH0_CLIENT_ID=${{ secrets.WL_PROD_AUTH0_CLIENT_ID }}
            export VITE_AUTH0_ORGANIZATION_ID=${{ secrets.WL_PROD_AUTH0_ORGANIZATION_ID }}
          elif [[ "${GITHUB_REF_NAME}" == "wm-prod" ]]; then
            export VITE_AUTH0_CLIENT_ID=${{ secrets.WM_PROD_AUTH0_CLIENT_ID }}
            export VITE_AUTH0_ORGANIZATION_ID=${{ secrets.WM_PROD_AUTH0_ORGANIZATION_ID }}
          else
            export VITE_AUTH0_CLIENT_ID=${{ secrets.DEV_AUTH0_CLIENT_ID }}
            export VITE_AUTH0_ORGANIZATION_ID=${{ secrets.DEV_AUTH0_ORGANIZATION_ID }}
          fi

          # build images using docker compose
          docker compose build

          # push images to docker hub
          docker compose push

      - name: Deploy Application to EC2 Instance
        env:
          CARNOT_DB_PASSWORD: ${{ secrets.CARNOT_DB_PASSWORD }}
          CARNOT_DB_USER: ${{ secrets.CARNOT_DB_USER }}
          CARNOT_DB_NAME: ${{ secrets.CARNOT_DB_NAME }}
          CARNOT_DEPLOY_KEY: ${{ secrets.CARNOT_DEPLOY_KEY }}
        run: |
          echo "Deploying to EC2 Instance at $EC2_PUBLIC_IP"

          # Prepare deploy directory
          mkdir -p deploy/compose/secrets
          echo "$CARNOT_DB_PASSWORD" > deploy/compose/secrets/db_password.txt
          echo "$CARNOT_DB_USER" > deploy/compose/secrets/db_user.txt
          echo "$CARNOT_DB_NAME" > deploy/compose/secrets/db_name.txt
          chmod 600 deploy/compose/secrets/db_*.txt

          # Prepare deploy environment variables
          echo "DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}" >> deploy/compose/.env
          echo "ENV_NAME=${ENV_NAME}" >> deploy/compose/.env
          echo "LOCAL_ENV=false" >> deploy/compose/.env
          echo "SETTINGS_ENCRYPTION_KEY=${{ secrets.SETTINGS_ENCRYPTION_KEY }}" >> deploy/compose/.env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_CUSTOM_DOMAIN }}" >> deploy/compose/.env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> deploy/compose/.env
          echo "AUTH0_CLAIMS_NAMESPACE=${{ secrets.AUTH0_CLAIMS_NAMESPACE }}" >> deploy/compose/.env
          echo "BASE_ORIGINS=http://${SUBDOMAIN}.carnot-research.org,https://${SUBDOMAIN}.carnot-research.org,http://web-backend,https://web-backend" >> deploy/compose/.env

          # Copy compose bundle to EC2
          scp -r -o StrictHostKeyChecking=no -i deployer_key.pem deploy/compose ubuntu@$EC2_PUBLIC_IP:~/

          # Shutdown current docker containers
          ssh -o StrictHostKeyChecking=no -i deployer_key.pem ubuntu@$EC2_PUBLIC_IP "
            cd compose
            docker compose down
            docker rmi -f $(docker images -aq)
            docker system prune -af
          "

          # Login & deploy using pulled images
          ssh -o StrictHostKeyChecking=no -i deployer_key.pem ubuntu@$EC2_PUBLIC_IP "
            cd compose
            docker login -u '${{ vars.DOCKERHUB_USERNAME }}' -p '${{ secrets.DOCKERHUB_TOKEN }}'
            docker compose pull
            docker compose up -d
          "
